const header = {
  connectButton: {
    connectWallet: 'Connect Wallet',
    wrongNetwork: 'Wrong Network',
    myIdeas: 'View My Dreams',
    logout: 'Logout',
    connectedTo: 'Connected to',
  },
  searchIdeas: {
    placeholder: 'Search for Dreams',
    noIdeasFound: 'No Dreams found',
  },
}

const notFound = {
  heading: 'Something went wrong',
  subHeading1: 'Brace yourself till we get the error fixed',
  subHeading2: 'You may also refresh the page or try again later',
  buttonTitle: 'Return Home',
}

const footer = {
  terms: 'Terms',
  aboutUs: 'About Web3It.AI',
  privacyPolicy: 'Privacy',
  contactUs: 'Contact us',
  contactUsModal: {
    heading: 'Contact Us',
    submitButton: 'Send',
    youCanContact: 'You can contact us at',
  },
}

const createIdea = {
  categories: {
    noTagsFound: 'No Categories found',
  },
  insufficientBalance: 'You have insufficient balance to create a dream',
  reservedDomain: 'This domain is reserved. Please choose another ticker',
  heading: 'Create Token',
  subHeading: 'Launch Your Dream',
  subHeadingCreated: 'Design Your Dream',
  subHeadingFundingReached: 'Funding Reached',
  subHeading2: 'Share your dream in detail to connect with potential believers',
  subHeading2FundingReached: "You can't edit this dream anymore to protect the initial idea",
  tokenCreationFeeLabel: 'One time fee',
  maxSupplyLabel: 'Max supply',
  initialMintLabel: 'Initial supply',
  tokensSuffix: ' tokens',
  targetInfoPart1: 'If funding target of ',
  targetInfoPart2: 'is met, a liquidity pool will be created on Uniswap.',
  ideaNotFound: "Dream not found!",
  ideaCreatedMessage: 'Dream successfully created!',
  ideaDetailsUpdated: 'Dream details updated!',
  errorOccurred: "Something went wrong. Please try again!",
  cantEditError: "You can't update as you are not the owner of this dream!",
  validationErrors: {
    nameRequired: 'Please enter a name for your dream',
    nameMinError: 'Please enter more than 2 characters',
    nameMaxError: 'Please enter less than 20 characters',
    tickerRequired: 'Please enter a name for your ticker',
    tickerMinError: 'Please enter more than 2 characters',
    tickerMaxError: 'Please enter less than 20 characters',
    logoRequired: 'Please upload logo or image depicting your dream',
    descriptionRequired: 'Please provide a description for your dream',
    descriptionMinError: 'Please enter more than 10 characters',
    descriptionMaxError: 'Please enter less than 1000 characters',
    categoriesRequired: 'Please select a category',
    websiteRequired: 'Please provide a valid link',
    twitterInvalid: 'Please provide a valid X link',
    telegramInvalid: 'Please provide a valid telegram link',
  },
  imageUpload: {
    title: 'Dream Logo',
    imageSizeError: 'Please upload image less than 5 mb',
    imageType: 'This is a wrong file format. Only image files are allowed.',
    uploadError: 'Could not add file. Please try again.',
    uploading: 'Uploading...',
    uploadLabel: 'Upload here',
  },
  form: {
    name: 'Dream title',
    address: 'Address',
    ticker: 'Ticker name',
    description: 'Core vision',
    category: 'Select category',
    website: 'Website',
    websitePreview: 'Dream preview',
    twitter: 'X(Twitter)',
    telegram: 'Telegram',
    submitLabel: 'Submit',
    connectWallet: 'Connect Wallet',
    brandingDetails: 'Dream Identity',
    dreamDetails: 'Describe your Dream',
    generateButtonLabel: 'Restart',
    optional: 'Recommended',
    communityChannels: 'Community Channels',
    createIdea: 'Create Dream',
    confirm: 'Confirm',
    subdomainExisting: 'Please note you will be assigned a alternate subdomain as this subdomain is already taken',
  },
}

const generateIdea = {
  promptPlaceholders: [
    "Create the next Decentralized Social Media Platform",
    "Create an AI-Driven Marketplace for Digital Assets",
    "Create a DAO Management Platform",
    "Create a Blockchain-Based E-Learning Platform",
    "Create a Smart Contract Development Assistant",
  ],
  promptLoadingStates: [
    {
      text: "Exploring Concepts",
    },
    {
      text: "Developing Blueprint",
    },
    {
      text: "Designing Brand Identity",
    },
    {
      text: "Crafting User Experience",
    },
    {
      text: "Refining Design Elements",
    },
    {
      text: "Building Social Strategy",
    },
    {
      text: "Finalizing and Deploying",
    },
  ],
  greeting: {
    morning: "Good morning, tell me about your Dream",
    afternoon: "Good afternoon, tell me about your Dream",
    evening: "Good evening, tell me about your Dream",
  },
  whatsYourDream: "Tell me about your Dream",
  generateError: 'Something went wrong. Please try again later.',
  poweredBy: 'powered by',
  readyTo: 'You are one step away from transforming your Dreams into reality',
  continue: 'Continue to Create Token',
  proceed: 'Proceed',
  orEnhance: 'Or keep enhancing the dream',
  h1: 'Generate your Web3 Dream with Claude AI',
}

const ideas = {
  ideaCard: {
    raised: 'Raised',
    holders: 'Believers',
  },
  currentIdeas: 'Dreams Gallery',
  currentIdeasSubHeading: 'Discover innovative dreams ready for community support',
  noIdeasHeading: 'No dreams yet in this category',
  noIdeasSubHeading: 'Be the first to contribute! Share your innovative dreams and help to grow this category.',
  registerIdea: 'Fund Existing Dream',
  launchNew: 'Generate Dream',
}

const homePage = {
  timeline: {
    heading: 'How to Launch Your Dream?',
    subHeading: 'Transform your dream into a fully functional application with our AI-powered launch strategy',
  },
  subHeading: 'Turn your inspiration into tangible impact.',
  h1: 'Make your Dreams Come True',
  subHeading1: "Web3it.ai is built with a goal of helping millions of talented developers around the world.",
  subHeading2: 'You can access the power of Web3 and AI in one click.',
  subHeading3: "Web2 developers can simply share their existing product idea or a new idea and Web3it instantly tokenizes the product and fair launches it on a bonding curve. Web3it also launches an AI Marketing agent and an AI Dev agent that infuses their Web2 product (now Web3) with powerful AI capabilities - all out of the box.",
  heroWords: [
    {
      text: "Make",
    },
    {
      text: "your",
    },
    {
      text: "Dreams",
      className: "gradientText",
    },
    {
      text: "Come",
    },
    {
      text: "True",
    },
  ],
  fundButtonLabel: 'Fund Existing Dream',
  generateButtonLabel: 'Generate Dream',
  trendingIdeas: 'Dreams In Action',
  dreamGallery: 'Dreams Gallery',
  stats: {
    heading: 'Dreams Overview',
    description: 'Look at how the community is growing and the impact we are making together',
    dreamsLaunched: 'have been launched so far',
    fundsRaised: 'have been raised so far to support these dreams',
    activeAgents: 'have been running in the background',
  },
  developmentProcess: {
    heading: 'Process',
    stepOneTitle: 'Dream Validation',
    stepOneInfo: "From raw concept to refined vision",
    stepOnePoints: `AI-enhanced ideation 💡 with expert community feedback 💬 and direct market validation from target users 🎯`,
    stepTwoTitle: 'AI-Powered Development',
    stepTwoInfo: "Where vision meets execution",
    stepTwoPoints: `Rapid development with our AI-powered IDE 💻 and real-time community-driven validation 💬`,
    stepThreeTitle: 'Sustainable Launch',
    stepThreeInfo: "Built for lasting impact",
    stepThreePoints: `Customized token economics 💰, engaged early users 👥 and proven growth strategies 📈`,
    stepFourTitle: 'Accelerated Growth',
    stepFourInfo: 'Scaling with purpose',
    stepFourPoints: `Access strategic partnerships 🤝, expand market reach 🌐 and track measurable impact 📊`,
  },
}

const ideaPage = {
  createdBy: 'Created by',
  tokenAddress: 'Token address',
  fundingRaised: 'Raised',
  visitWebsite: 'View website',
  conversations: 'Comments',
  post: 'Post',
  noComments: 'No comments yet. Be the first to start the conversation!',
  preview: 'Preview',
  buyFeed: 'Buy Feed',
  sellFeed: 'Sell Feed',
  owners: 'Owners',
  chart: 'Buy Trend',
  stakeholders: 'Believers',
  stakeholdersDesc: 'Our visionary believers making this dream possible ✨',
  checkTransHeading: 'Check out ongoing trades on',
  transactionsTable: {
    columnOne: 'Account',
    columnTwo: 'Value',
    columnThree: 'Time',
    columnFour: 'Transaction',
  },
  ownersTable: {
    columnOne: 'Account',
    columnTwo: 'Percentage',
  },
  limitedTokensError: 'Limited tokens. There is only %amount% tokens left.',
  purchaseSuccess: 'Congratulations! You have purchased',
  purchaseError: 'Purchase could not be completed. Please try again!',
  bondingCurveProgress: 'Progress',
  buyTokensFor: 'Buy tokens for',
  availableTokens: 'Available tokens',
  purchaseLabel: 'Get Quote',
  youWillReceive: 'You will receive',
  maxButton: 'Max',
  deleteComment: 'Delete comment',
  areYouSureToDelete: 'Are you sure you want to delete this comment?',
  editIdea: 'Edit',
  boostIdea: 'Accelerate Dream',
  confirm: 'Confirm',
  for: 'for',
  confirmPurchase: 'Confirm purchase',
  buyTokens: 'Support Dream',
  buy: 'Buy',
  remaining: ' Remaining',
  swapTokens: 'Swap Tokens',
  swapTokensDesc: 'You can buy/sell tokens from the liquidity pool',
  openUniswap: 'Open in Uniswap',
  connectWallet: 'Connect Wallet',
  swapping: 'Swapping...',
  swap: 'Swap',
  buyTokensDesc: 'Join our community and shape the future - get tokens now 🚀',
  ensure: 'Ensure you have enough funds in your account',
  likelyFail: 'Note: This transaction will likely fail as you do not have enough funds',
  buyNow: 'Confirm',
  bondingCurveInfo: "When the market cap reaches %goal% %currency%, all the liquidity from the bonding curve will be deposited into Uniswap, and the LP tokens will be burned. Progression increases as the price goes up.",
}

const profile = {
  heading: 'Dream Portfolio',
  startAllAgents: 'Start All Agents',
  subheading: "Track your dream's progress and manage your launch strategy",
  noIdeasHeading: 'You have not created any Dream',
  noIdeasSubHeading: 'Create your first Dream',
  registerIdea: 'Fund Existing Dream',
  launchNew: 'Generate Dream',
  table: {
    ideaName: 'Dream name',
    status: 'Status',
    ideaAddress: 'Address',
    ticker: 'Ticker',
    actions: 'Actions',
    view: 'View',
    review: 'Accelerate Dream',
    edit: 'Customize',
  },
}
const manageIdea = {
  heading: 'Accelerate your Dream',
  subHeading: 'Meet your personal team of AI experts, each uniquely trained to help transform different aspects of your vision into reality.',
  twitterDescription: 'This agent will create a personalized persona based on your dream which will schedule tweets, handle replies, and more.',
  tweets: 'Tweets Generated',
  tweetsSingular: 'Tweet Generated',
  engagement: 'Engagement metrics',
  manageAgent: 'Manage Agent',
  modifyCharacter: 'Agent Personality',
  agentSettings: 'Engagement Settings',
  devAgent: 'Dev Agent',
  openAgent: 'Open Agent',
  createSandbox: 'Create Sandbox',
  openSandbox: 'Open Sandbox',
  addNewDev: 'Add New',
  back: 'Back to Dream',
  devAgentDesc: 'The Dev Agent is a powerful tool that helps you build your dream. It provides you with a sandbox environment to develop your code and deploy your dream.',
  enableFollowing: 'Enable Following',
  enableFollowDescription: 'Allow agent to follow relevant accounts',
  enableActions: 'Enable Interactions',
  enableActionsDescription: 'Check and engage with tweets',
  enablePosts: 'Enable Tweeting',
  postInterval: 'Post Interval',
  postIntervalDesc: 'Duration between each tweet',
  interactionInterval: 'Interaction Interval',
  interactionIntervalDesc: 'Frequency of interactions(likes, retweets, replies)',
  followInterval: 'Follow Interval',
  followIntervalDesc: 'Frequency of following new accounts',
  enablePostsDescription: 'Allow agent to post personalized tweets',
  replies: 'Replies to Tweets',
  repliesSingular: 'Reply to Tweets',
  likes: 'Tweets Liked',
  likesSingular: 'Tweet Liked',
  retweets: 'Tweets Retweeted',
  retweetsSingular: 'Tweet Retweeted',
  followers: 'New Account Gained',
  followersSingular: 'New Accounts Gained',
  prev: 'Prev',
  next: 'Next',
  skip: 'Skip',
  twitterForm: {
    username: 'Username',
    password: 'Password',
    email: 'Email',
    submit: 'Start Agent',
    connect: 'Connect Wallet',
    stopAgent: 'Stop Agent',
    viewCharacter: 'View Settings',
    updateCharacter: 'Update Character',
    hideCharacter: 'Hide Settings',
    agentRunning: 'Running since',
  },
  character: {
    exampleOne: 'Example 1',
    exampleTwo: 'Example 2',
    exampleUserLabel: 'User',
    exampleAgentLabel: 'Agent',
    styleAll: 'All',
    styleChat: 'Chat',
    stylePost: 'Post',
    professional: 'Professional',
  },
  promptLoadingStates: [
    {
      text: "Crafting Your Digital Identity",
    },
    {
      text: "Preparing Your Agent",
    },
    {
      text: "Processing Platform Data",
    },
    {
      text: "Designing Engagement Plan",
    },
    {
      text: "Optimizing Post Schedule",
    },
  ],
  devLoadingStates: [
    {
      text: "Creating Sandbox",
    },
    {
      text: "Deploying Agent",
    },
    {
      text: "Building Dream",
    },
    {
      text: "Testing Dream",
    },
    {
      text: "Launching Dream",
    },
  ],
}

export const lang = {
  header,
  profile,
  createIdea,
  manageIdea,
  homePage,
  ideas,
  generateIdea,
  footer,
  notFound,
  ideaPage,
};

export default lang;
